QUOTES = [
  "the journey to a thousand flowers, starts with a single water!",
  "just keep swimming!",
  "love is a decision; not an emotion!",
  "the roots of all goodness lie in the soil of appreciation for goodness!",
  "we are but drops ebbing and flowing in the river of life!",
  "in the larger scheme of things, we mean nothing, we find true purpose by looking at the smaller things in life and doing our best!",
  "one cannot fire an arrow without first drawing it back!",
  "there may seem to be many otter things are important, but that doesn't mean you aren't!",
  "time used for fun is time well-spent!",
  "a drop of fresh water may not mean much in the vast ocean, but a drop of fresh water in the mouth of a parched person make a lot of difference!",
  "you’re totally pearl-fect!",
  "you’re awesome! My little bug friends agree!",
  "boom, surprise prezzie!",
  "here’s a sun peanutbutter fish just for you!",
  "at this rate, you’re going to be the next big pop star craze!",
  "you’re an international phenomenon!",
  "you’re kind of a big deal!",
  "I a-peach-iate you!",
  "orange you just the best!",
  "you’re apple-ley awesome!",
  "you’re a pear-fect friend!",
  "you’re cherry cool!",
  "a Redd visit a day, keeps the doctor away!",
  "if you were a butterfly, you’d be the majestic Queen Alexandra’s Birdwing!",
  "you are the icing on my cupcake!",
  "may Redd always bring you real art!",
  "have a sunshiney day!",
  "in the cookie of life, friends are the chocolate chips!",
  "you’re one in a melon!",
  "keep vibin’ and thrivin’!",
  "you are a flamingo in a flock of pigeons!",
  "you’re shrimply the best!",
  "you’re super eggs-cellent!",
  "you deserve the rest of the day off!",
  "you are a hoot!",
  "you are better than unicorns and sparkles combined!",
  "you are solid gold!",
  "may every rock you hit give you a gold nugget!",
  "if dogs are man’s best friend, then cats are man’s worst enemy!",
  "you’re totally rad, maaaan!",
  "I think you’re the bees knees!",
  "if life gives you lemons, you now have free lemons! Yay!",
  "remember to be nice to yourself, life is hard enough as it is!",
  "if you are what you eat, then go eat a star, because that’s what you are!",
  "do you know that you can perform at a meeting, but also meet at a performance? Wild!",
  "if life gives you lemons, plant those lemons. Hire more people, plant more lemons. Sell all the lemons. Create your own lemon empire. You are lemon royalty! Hail the new lemon overlord!"
]

ITEMS = [
  "a Sea Bass, yikes!",
  "a golden nuggie!",
  "a soggy banana!",
  "a single cooked anchovy!",
  "a squashed mosquito!",
  "a signed autograph by CJ!",
  "Raymond’s fleas in a jar! Extra valuable, please do not open the jar!",
  "a snowflake, oh no it melted already! It’s just water now...",
  "Isabelle’s single pink sock, freshly washed!",
  "Redd’s used bubblegum!",
  "a yellow butterfly! Now to catch a toastfly!",
  "Sherb’s half-eaten donut! Aw, that’s nice of him.",
  "Zucker’s homemade takoyaki ball! It’s not cannibalism if you eat it!",
  "Marshall’s pocket lint! He drops it into your hands smugly.",
  "Marina’s seashell! Shall we see what the shell sees?",
  "Bob’s candy! No wait, it’s just a candy wrapper...",
  "Audie’s spare sunglasses! Wait, one side is missing the lens...",
  "Beau’s house! Wait, you can’t give that away, Beau!!",
  "Judy’s receipt from Able’s! It says here that Judy bought a crown...",
  "Fauna’s hug! Aw, that’s sweet!",
  "Coco’s coconut! Nobody ask where she got it from!!!",
  "Stitches’ rags! Um...",
  "Lucky’s lucky coin! Is it still lucky if given away?",
  "Molly’s favourite teacup! Fits your hands to a T!",
  "Merengue’s strawberry! (Please don’t ask where she harvested it.)",
  "Lolly’s lollipop, only slightly licked!",
  "a ticket to watch Dom working out for 5 minutes!",
  "Cherry’s love and support! Aneki always has your back!",
  "Goldie’s favourite ball! I think she wants you to play with her...",
  "Ankha’s solemn nod! She didn’t even bother to look at you...",
  "Julian’s wink! Is it really a wink if he had his eyes closed the entire time?",
  "Pietro’s words of wisdom! He whispers it in your ear, but you immediately forget what it is. Hmm...",
  "Apollo’s feather! 9999 more of these, and you can fill a pillow!",
  "Tangy’s basket of oranges! Orange you glad it’s freshly plucked?",
  "Ketchup’s bowl of tomatoes! Is it toe-may-toe or toy-mah-toe?",
  "Apple’s handful of apples! She has small hands, so you receive only 2 apples.",
  "Skye’s photo of a cloud! Or is this a photo of her forehead?",
  "Tia’s cup of tea! Uh, where did the tea come from?",
  "Cookie’s homemade baked cookie! I hope it tastes like cookie and not Cookie...",
  "Octavian’s moon dust! Ops, you didn’t catch it quick enough and they floated away in the wind...",
  "an invite to Lily’s pad!",
  "Celeste, because you are a star!",
  "Orville, wuh-oh!",
  "Pecan’s freshly baked pie!",
  "Peanut’s jelly!",
  "a blue rose!",
  "a Whale Shark, thar she blows!",
  "a water egg!",
  "ten scallops!",
  "Ribbot’s loose screws! Wait, take those screws back, you’re falling apart!!!",
  "a tasty macaron!",
  "lots of puppy kisses!",
  "a golden toilet!",
  "a stack of sticks!",
  "a stack of stone!",
  "a stack of iron!",
  "a swarm of angry bees, AHHH!",
  "a single chicken nugget!",
  "a stack of turnips!",
  "a rotten turnip! Ugh!!"
]

EMOJIS = [
  "🥳",
  "🥰",
  "😌",
  "🙏",
  "🐶",
  "🐼",
  "🐻",
  "😎",
  "⭐️",
  "🍕",
  "🎈",
  "❤️",
  "💛",
  "💚",
  "💙",
  "😇",
  "🐠",
  "🏆",
  "⛲️",
  "💫",
  "🌟",
  "🦋",
  "🍀",
  "🐝",
  "☀️",
  "🐤"
]

class Handshake < ActiveRecord::Base
  belongs_to :thanker, class_name: "User"
  belongs_to :thankee, class_name: "User"

  def generate_message
    rand > 0.5 ? quote_message : thanks_message
  end

  def quote_message
    "#{thanker.mention} has thanked #{thankee.mention}! Hey #{thankee.discord_name}, " + QUOTES.sample + " " + EMOJIS.sample
  end

  def thanks_message
    "#{thanker.mention} has thanked #{thankee.mention}! #{thankee.discord_name} receives " + ITEMS.sample + " " + EMOJIS.sample
  end
end


