QUOTES = [
  "the journey to a thousand flowers, starts with a single water!",
  "just keep swimming!",
  "love is a decision; not an emotion!",
  "the roots of all goodness lie in the soil of appreciation for goodness!",
  "we are but drops ebbing and flowing in the river of life!",
  "in the larger scheme of things, we mean nothing, we find true purpose by looking at the smaller things in life and doing our best!",
  "one cannot fire an arrow without first drawing it back!",
  "there may seem to be many otter things are important, but that doesn't mean you aren't!",
  "time used for fun is time well-spent!",
  "a drop of fresh water may not mean much in the vast ocean, but a drop of fresh water in the mouth of a parched person make a lot of difference!",
  "you’re totally pearl-fect!",
  "you’re awesome! My little bug friends agree!",
  "boom, surprise prezzie!",
  "here’s a sun peanutbutter fish just for you!",
  "at this rate, you’re going to be the next big pop star craze!",
  "you’re an international phenomenon!",
  "you’re kind of a big deal!",
  "I a-peach-iate you!",
  "orange you just the best!",
  "you’re apple-ley awesome!",
  "you’re a pear-fect friend!",
  "you’re cherry cool!",
  "a Redd visit a day, keeps the doctor away!",
  "if you were a butterfly, you’d be the majestic Queen Alexandra’s Birdwing!",
  "you are the icing on my cupcake!",
  "may Redd always bring you real art!",
  "have a sunshiney day!",
  "in the cookie of life, friends are the chocolate chips!",
  "you’re one in a melon!",
  "keep vibin’ and thrivin’!",
  "you are a flamingo in a flock of pigeons!",
  "you’re shrimply the best!",
  "you’re super eggs-cellent!",
  "you deserve the rest of the day off!",
  "you are a hoot!",
  "you are better than unicorns and sparkles combined!",
  "you are solid gold!",
  "may every rock you hit give you a gold nugget!",
  "if dogs are man’s best friend, then cats are man’s worst enemy!",
  "you’re totally rad, maaaan!",
  "I think you’re the bees knees!",
  "if life gives you lemons, you now have free lemons! Yay!",
  "remember to be nice to yourself, life is hard enough as it is!",
  "if you are what you eat, then go eat a star, because that’s what you are!",
  "do you know that you can perform at a meeting, but also meet at a performance? Wild!",
  "if life gives you lemons, plant those lemons. Hire more people, plant more lemons. Sell all the lemons. Create your own lemon empire. You are lemon royalty! Hail the new lemon overlord!",
  "you won BOTH socks! Look at you go!",
  "Zipper is here! Quick! Hide before he sees you!",
  "please enjoy the satisfaction of being thanked!",
  "isn’t altruism great?",
  "it a-pears that you have done good. Good job!"
]

ITEMS = [
  "a Sea Bass, yikes!",
  "a golden nuggie!",
  "a soggy banana!",
  "a single cooked anchovy!",
  "a squashed mosquito!",
  "a signed autograph by CJ!",
  "Raymond’s fleas in a jar! Extra valuable, please do not open the jar!",
  "a snowflake, oh no it melted already! It’s just water now...",
  "Isabelle’s single pink sock, freshly washed!",
  "Redd’s used bubblegum!",
  "a yellow butterfly! Now to catch a toastfly!",
  "Sherb’s half-eaten donut! Aw, that’s nice of him.",
  "Zucker’s homemade takoyaki ball! It’s not cannibalism if you eat it!",
  "Marshall’s pocket lint! He drops it into your hands smugly.",
  "Marina’s seashell! Shall we see what the shell sees?",
  "Bob’s candy! No wait, it’s just a candy wrapper...",
  "Audie’s spare sunglasses! Wait, one side is missing the lens...",
  "Beau’s house! Wait, you can’t give that away, Beau!!",
  "Judy’s receipt from Able’s! It says here that Judy bought a crown...",
  "Fauna’s hug! Aw, that’s sweet!",
  "Coco’s coconut! Nobody ask where she got it from!!!",
  "Stitches’ rags! Um...",
  "Lucky’s lucky coin! Is it still lucky if given away?",
  "Molly’s favourite teacup! Fits your hands to a T!",
  "Merengue’s strawberry! (Please don’t ask where she harvested it.)",
  "Lolly’s lollipop, only slightly licked!",
  "a ticket to watch Dom working out for 5 minutes!",
  "Cherry’s love and support! Aneki always has your back!",
  "Goldie’s favourite ball! I think she wants you to play with her...",
  "Ankha’s solemn nod! She didn’t even bother to look at you...",
  "Julian’s wink! Is it really a wink if he had his eyes closed the entire time?",
  "Pietro’s words of wisdom! He whispers it in your ear, but you immediately forget what it is. Hmm...",
  "Apollo’s feather! 9999 more of these, and you can fill a pillow!",
  "Tangy’s basket of oranges! Orange you glad it’s freshly plucked?",
  "Ketchup’s bowl of tomatoes! Is it toe-may-toe or toy-mah-toe?",
  "Apple’s handful of apples! She has small hands, so you receive only 2 apples.",
  "Skye’s photo of a cloud! Or is this a photo of her forehead?",
  "Tia’s cup of tea! Uh, where did the tea come from?",
  "Cookie’s homemade baked cookie! I hope it tastes like cookie and not Cookie...",
  "Octavian’s moon dust! Ops, you didn’t catch it quick enough and they floated away in the wind...",
  "an invite to Lily’s pad!",
  "Celeste, because you are a star!",
  "Orville, wuh-oh!",
  "Pecan’s freshly baked pie!",
  "Peanut’s jelly!",
  "a blue rose!",
  "a Whale Shark, thar she blows!",
  "a water egg!",
  "ten scallops!",
  "Ribbot’s loose screws! Wait, take those screws back, you’re falling apart!!!",
  "a tasty macaron!",
  "lots of puppy kisses!",
  "a golden toilet!",
  "a stack of sticks!",
  "a stack of stone!",
  "a stack of iron!",
  "a swarm of angry bees, AHHH!",
  "a single chicken nugget!",
  "a stack of turnips!",
  "a rotten turnip! Ugh!!",
  "yet another Sea Bass!",
  "something that doesn't look like a scallop. Wait. It's a Sea Bass!",
  "two whole socks! Look at you go!",
  "the satisfaction of being thanked",
  "an entire box of off-brand cereal",
  "another Floral Swag DIY",
  "one of Olaf’s rejected nose-carrots...",
  "a book of Raymond’s fanfiction!",
  "the dust of 100 dogs...",
  "a mouse-sized umbrella!",
  "the record of a spaceborn few?",
  "a Martian potato!",
  "the secrets of the universe, discovered by Aristotle and Dante.",
  "the ability to write text perfectly backwards!",
  "an unopened, 10-year-old soda!?",
  "dinner for breakfast!",
  "cherry cake from a party thrown by Cherry, Cheri, and Shari!",
  "peaches fresh from Peaches’s ranch!",
  "Rocket’s bodysuit...?",
  "a plate of hard spaghetti, which fills you with determination!",
  "a Junimo plushie!",
  "cherry chapstick!",
  "the catcher in the rye?",
  "half of a grapefruit!",
  "the hair from someone’s haircut...",
  "Zuko’s ponytail!",
  "a zipper that looks oddly familiar...",
  "that favorite jacket of yours that you lost ages ago!",
  "|| :sparkles: :nose: :sparkles: ||!",
  "Yxaj’s mirror. Wait, that’s Jaxy inside!",
  "a lone celery stick!",
  "a surprise fish stick!",
  "an emergency sewing kit!",
  "a knot guidebook!",
  "knee-high rainbow socks!",
  "not a can, but a can’t of tuna!",
  "a watering can labelled “Moisk Machine” on the side!",
  "a full set of brand-new micro-pipetters!",
  "whatever it is, it’s at least a C+!",
  "everyone’s love and support!",
  "a mysterious doorway with another world on the other side...",
  "a GREAT hair day!",
  "manila ice cream!",
  "a small cactus, but the spines are porcupine quills instead...?",
  "a fruits basket!",
  "a red-and-white-striped shirt. Wait, Waldo?!",
  "a yellow kitchen sponge next to a pink starfish!",
  "a double-headed coin!",
  "a rotary cell phone!",
  "Sherb’s sherbet! Wait, this is half-eaten already!",
  "Maggie’s library. Wait! Wrong Maggie!",
  "Boots’s boot!",
  "Gayle’s wind! Wait, what does that mean?",
  "Pango’s mangoes!",
  "Beardo’s bread-os! Is that some kind of sad cereal?",
  "chow from Chow!",
  "Tutu’s tutu!",
  "a pizza from Anchovy!",
  "Jacob’s ladder! Did he buy this at Nook’s Cranny?",
  "Jitters’s coffee! Maybe he should try some taurine or ginseng with his coffee?",
  "Peck’s peck of pickled peppers!",
  "a pipe from Piper! Cici n’est pas une pipe.",
  "Robin’s mask. Does she know Batman?",
  "Sparro’s pair-o’ pants! I didn’t know birds wore pants!",
  "Twiggy’s twigs! Is this from her nest?",
  "Angus’s buns!",
  "Rodeo’s lasso! Yee-haw!",
  "stew from Stu! It’s surprisingly delicious!",
  "a mysterious book and robe from Kiki!",
  "Punchy’s punch! It’s delicious but makes you feel fUNnY...",
  "Olivia’s olives! There are two green ones on a toothpick.",
  "Purrl’s knitting project! It’s almost complete!",
  "a pink rose from Rosie!",
  "Benedict’s breakfast! It’s delicious and pricy.",
  "a swan from Goose, the chicken!",
  "Ken’s picture of Barbie!",
  "Knox’s door. He wants you to knox it.",
  "Patty’s cake, baker’s man!",
  "just Tipper’s tip!",
  "a barrel from Barold!",
  "Bluebear’s muffin! Is it Sunday?",
  "Chester’s chest of drawers! Are there clothes in here too?",
  "Judy’s mood ring!",
  "June’s bug! What kind of bug is it? A junebug!",
  "a stack of pancakes! Made by Maple, of course!",
  "Murphy’s bed! It folds up into the wall!",
  "Poncho’s raincoat! It’s big, but it keeps you dry.",
  "a white cosmos from Daisy!",
  "Mac’s cheese. It’s goooooey!",
  "Scoot’s hat! Or is this underwear...?",
  "wait, what is it? I swear I saw a frog shape but there’s nothing there?",
  "Drift’s joycons... oh jeez!",
  "Huck’s berries and fins!",
  "Raddle’s PPE! Stay safe out there, and wear a mask!",
  "Tad’s gossip! You find out just a tad.",
  "Nan and Nana’s banana bread!",
  "Cesar’s salad!",
  "Clay’s pot! I can craft one of those!",
  "Flurry’s snowflake! It’s unique!",
  "a s’more from Graham!",
  "Hippeux’s chapeau... it’s all greasy...",
  "a bell bag from Bill, Billy, and Buck!",
  "Elmer’s glue. Wait... how did he get this?",
  "Alice’s rabbit. It looks like Ruby and keeps saying it’s late!",
  "Lyman’s limes! They’re super juicy!",
  "Melba’s vegemite! You can’t decide if you like it or not.",
  "Bud’s friendship! If you’ll let him be your bud.",
  "Deli’s sandwich! He sure knows how to make ‘em.",
  "Flip’s flip-flops! Why does a monkey need shoes?",
  "Simon’s instructions! You better do what he says, or you’ll be out!",
  "Broccolo’s broccoli. He doesn’t know how to cook broccoli.",
  "Dora’s Explorer Hat! Swiper no swiping!",
  "Cube’s pyramid of spheres! Only a square would have that!",
  "Puck’s hockey stick! You think he’d be good at playing hockey, but...",
  "Roald’s rolled oats! Is this what he has for breakfast each day?",
  "Tex’s tux! He looks better in a cowboy shirt anyway.",
  "Wade’s shallow pool! You can’t wade in the deep end, after all.",
  "Chops’s chopper! He must be rich to be giving this away!",
  "Gala’s ball! It’s a rather fun event!",
  "Hugh’s hue, it’s a strong blue!",
  "Spork’s spork, it’s better than a fork!",
  "Truffles’s puffle! Wait, she plays Club Penguin too?!",
  "Chrissy’s sissy! Wait, that’s Francine!",
  "a lump of coal from Cole. Thanks.",
  "Doc’s documents! What do these say?",
  "Hopkins’s hot air! It blows away...",
  "Snake’s apple. You probably shouldn’t eat this one!",
  "Bangle’s bracelets! They jingle and jangle pleasantly."
]

EMOJIS = [
  "🥳",
  "🥰",
  "😌",
  "🙏",
  "🐶",
  "🐼",
  "🐻",
  "😎",
  "⭐️",
  "🍕",
  "🎈",
  "❤️",
  "💛",
  "💚",
  "💙",
  "😇",
  "🐠",
  "🏆",
  "⛲️",
  "💫",
  "🌟",
  "🦋",
  "🍀",
  "🐝",
  "☀️",
  "🐤"
]

PREFIX = [
  "Hey",
  "Hello",
  "Hi",
  "Yo",
  "Psst",
  "Greetings",
  "Hiya",
  "Hey, listen"
]

class Handshake < ActiveRecord::Base
  belongs_to :thanker, class_name: "User"
  belongs_to :thankee, class_name: "User"

  def generate_message(thankee_nickname)
    rand > 0.5 ? quote_message(thankee_nickname) : thanks_message(thankee_nickname)
  end

  def quote_message(thankee_nickname)
    "#{PREFIX.sample} #{clean_nickname(thankee_nickname)}, " + QUOTES.sample + " " + EMOJIS.sample
  end

  def thanks_message(thankee_nickname)
    "#{clean_nickname(thankee_nickname)} receives " + ITEMS.sample + " " + EMOJIS.sample
  end

  def clean_nickname(thankee_nickname)
    if thankee_nickname.include?("from")
      thankee_nickname.split("from").first.strip
    else
      thankee_nickname.split(" ").first
    end
  end
end


